### ISSUE TITLE
Wiki game version mistake

### ISSUE THREAD

**Issue by lstone01** [Drustcraft/Drustcraft-Game#8]
On the home page of the wiki it says that If you are playing Minecraft on a tablet (Android or iPad), on a Mac, you are using the Java version but you can only play java on a mac or windows. Mobile/tablet, console and the windows ten version are Bedrock not Java.

**Comment by nomadjimbob** [comment]
I cannot edit the wiki at the moment. I believe either the website or the API is not recognizing the group category change done in an update to the Drustcraft-Engine.

Previously, Minecraft groups where mixed between roles (`administrator`, `staff`, `builder`) and player groups (`isaac`, `ironport`). In a recent update, this was changed so that group names required a prefix to indicate what category the group is such as `role_` for roles, `tier_` for tiers, `builder_` for builder groups and `group_` for player groups.

**Comment by lstone01** [comment]
same with me

**Comment by nomadjimbob** [comment]
It appears to be at least a Drustcraft-Web issue seen here https://github.com/Drustcraft/Drustcraft-Website/blob/6610ccf02c13f7cc6060978b923d43b618570c96/src/views/WikiPage.vue#L31 the website is referencing the `staff` group.

**Comment by lstone01** [comment]
staff and not game masters?

**Comment by lstone01** [comment]
so you just have to rewrite that part?

**Comment by nomadjimbob** [comment]
Referencing groups may not be the best approach. Currently the Drustcraft-API connects to the Minecraft server database and 'copies' the LuckPerms groups of players into the API database. From that point onwards, the API and Website only uses groups (or now roles) as the permission mechanism. Maybe the API needs to also look for `web.xxx` permissions in LuckPerms and copy them across as well, with the API and website using `web.wiki` or other permissions instead of roles and groups.

This would allow granular permission control in the future as well as changing/adding/removing roles without the need of updating the API and Website of these changes (as its looking at permission base, not group/rolw base).

> staff and not game masters?
Staff was the group before the new roles prefix was introduced, which was the same time staff was changed to GM and Admin

> so you just have to rewrite that part?
A quick change will most likely be done to change the staff to role_gm to get the wiki editing operational again. The above change from groups to permissions will most likely be done down the road as it would be a bigger update.

**Comment by lstone01** [comment]
so i can just change it to role_gm?

**Comment by nomadjimbob** [comment]
Yes. As the vue build and deploy action is not yet implemented in this repo, it would need to be built manually using `npm run build` and the `css`, `js` and `index.html` uploaded to the web server.

**Comment by lstone01** [comment]
so its not that easy

**Comment by nomadjimbob** [comment]
<img width="301" alt="Screen Shot 2021-08-24 at 9 31 04 am" src="https://user-images.githubusercontent.com/26953208/130532346-2cd23496-7848-4ffd-ae36-8088849a35cf.png">

The API already has the correct group data in the API database

**Comment by nomadjimbob** [comment]
This should now be [fixed](https://github.com/Drustcraft/Drustcraft-Website/commit/22366c34fad28eb430caf3e2ddd074074265b700). Users may need to refresh the website to see the changes (1.0.17).

I will leave this issue open for the information about [changing from group to permission base](https://github.com/Drustcraft/Drustcraft-Game/issues/8#issuecomment-904202015)

**Comment by nomadjimbob** [comment]
The API has now been updated to support [roles](https://github.com/Drustcraft/Drustcraft-API/commit/f2ba7944c149fac571d1ed4b250fa1806facc76b) and I have changed the forum permissions to match

**Comment by lstone01** [comment]
ok, just fixing the wiki now

**Comment by nomadjimbob** [comment]
This can be closed once the wiki change has been completed @lstone01. Permission based recommendations mentioned above with the Website and API have now been created in those repos.

**Comment by lstone01** [comment]
ok

**Comment by lstone01** [comment]
Wiki is updated
